import dash
from dash import dcc, html, Input, Output
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import numpy as np

# Load the predictions generated by evaluate.py
data_path = r"c:/Users/bennn/localSchool/PINN/PINN-MME4469/results/SimTK_Predictions.xlsx"
try:
    df = pd.read_excel(data_path)
except Exception:
    print(f"Could not load data from {data_path}. Using dummy data.")
    x = np.linspace(1, 100, 100)
    df = pd.DataFrame({
        '% Gait Cycle': x,
        'Predicted_Fz': np.sin(x / 10) * 1000 + 500,
        'Predicted_F_Medial': np.sin(x / 10) * 600 + 300,
        'Predicted_F_Lateral': np.sin(x / 10) * 400 + 200
    })

# Gait phase boundaries (approximate %)
gait_phases = [
    {'name': 'Initial Contact', 'start': 0, 'end': 2, 'color': 'rgba(255,152,0,0.12)'},
    {'name': 'Loading Response', 'start': 2, 'end': 12, 'color': 'rgba(244,67,54,0.10)'},
    {'name': 'Mid Stance', 'start': 12, 'end': 31, 'color': 'rgba(76,175,80,0.10)'},
    {'name': 'Terminal Stance', 'start': 31, 'end': 50, 'color': 'rgba(33,150,243,0.10)'},
    {'name': 'Pre-Swing', 'start': 50, 'end': 62, 'color': 'rgba(156,39,176,0.10)'},
    {'name': 'Swing', 'start': 62, 'end': 100, 'color': 'rgba(255,235,59,0.08)'},
]

app = dash.Dash(__name__)

# ─── LAYOUT ────────────────────────────────────────────────────────────
app.layout = html.Div(style={
    'backgroundColor': '#0D1117', 'color': '#C9D1D9',
    'fontFamily': "'Inter', 'Segoe UI', sans-serif",
    'minHeight': '100vh', 'padding': '30px 40px'
}, children=[

    # Header
    html.Div([
        html.H1("Knee Joint Reaction Force Dashboard",
                style={'color': '#58A6FF', 'fontWeight': '600', 'fontSize': '1.8em',
                       'margin': '0', 'letterSpacing': '0.5px'}),
        html.P("PINN-LSTM Predictions  •  Synchronized Gait Scrubber",
               style={'color': '#8B949E', 'margin': '4px 0 0 0', 'fontSize': '0.95em'}),
    ], style={'borderBottom': '1px solid #21262D', 'paddingBottom': '18px', 'marginBottom': '24px'}),

    # Metric Cards
    html.Div(id='metric-cards', style={
        'display': 'grid', 'gridTemplateColumns': 'repeat(4, 1fr)', 'gap': '16px',
        'marginBottom': '24px'
    }),

    # Main Chart
    html.Div([
        dcc.Graph(id='force-chart', style={'height': '52vh'},
                  config={'displayModeBar': False})
    ], style={
        'backgroundColor': '#161B22', 'borderRadius': '12px',
        'border': '1px solid #21262D', 'padding': '12px',
        'boxShadow': '0 4px 20px rgba(0,0,0,0.3)'
    }),

    # Slider
    html.Div(style={
        'padding': '20px 30px', 'backgroundColor': '#161B22',
        'borderRadius': '12px', 'border': '1px solid #21262D',
        'marginTop': '16px', 'maxWidth': '900px', 'margin': '16px auto 0'
    }, children=[
        html.Div(style={'display': 'flex', 'justifyContent': 'space-between', 'alignItems': 'center'}, children=[
            html.Span("Gait Cycle Position", style={'color': '#8B949E', 'fontSize': '0.85em'}),
            html.Span(id='phase-label', style={'color': '#58A6FF', 'fontSize': '0.85em', 'fontWeight': '600'}),
        ]),
        dcc.Slider(
            id='gait-slider', min=1, max=100, step=1, value=25,
            marks={i: {'label': f'{i}%', 'style': {'color': '#484F58', 'fontSize': '11px'}}
                   for i in range(0, 101, 10)},
            tooltip={"placement": "bottom", "always_visible": True}
        )
    ])
])

# ─── HELPER: Build a metric card ──────────────────────────────────────
def make_card(label, value, unit, accent_color):
    return html.Div(style={
        'backgroundColor': '#161B22', 'borderRadius': '10px',
        'border': '1px solid #21262D', 'padding': '16px 20px',
        'textAlign': 'center'
    }, children=[
        html.Div(label, style={'color': '#8B949E', 'fontSize': '0.78em',
                               'textTransform': 'uppercase', 'letterSpacing': '1px',
                               'marginBottom': '6px'}),
        html.Div([
            html.Span(f"{value:.1f}", style={'color': accent_color, 'fontSize': '1.6em', 'fontWeight': '700'}),
            html.Span(f" {unit}", style={'color': '#484F58', 'fontSize': '0.85em'}),
        ])
    ])


# ─── CALLBACK ─────────────────────────────────────────────────────────
@app.callback(
    [Output('force-chart', 'figure'),
     Output('metric-cards', 'children'),
     Output('phase-label', 'children')],
    [Input('gait-slider', 'value')]
)
def update_dashboard(gait_pct):
    row = df.iloc[np.abs(df['% Gait Cycle'] - gait_pct).argmin()]
    fz = row['Predicted_Fz']
    f_med = row['Predicted_F_Medial']
    f_lat = row['Predicted_F_Lateral']

    # Determine current gait phase
    current_phase = 'Unknown'
    for p in gait_phases:
        if p['start'] <= gait_pct < p['end']:
            current_phase = p['name']
            break

    # ── Build stacked subplots ──
    fig = make_subplots(
        rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.06,
        subplot_titles=("Total Axial Force (Fz)", "Medial Contact Force", "Lateral Contact Force")
    )

    traces = [
        ('Predicted_Fz', '#58A6FF', 'Fz'),
        ('Predicted_F_Medial', '#3FB950', 'Medial'),
        ('Predicted_F_Lateral', '#F85149', 'Lateral'),
    ]

    for idx, (col, color, name) in enumerate(traces, 1):
        # Gait phase shading
        for p in gait_phases:
            fig.add_vrect(x0=p['start'], x1=p['end'], fillcolor=p['color'],
                          layer='below', line_width=0, row=idx, col=1)

        # Data trace
        fig.add_trace(go.Scatter(
            x=df['% Gait Cycle'], y=df[col], mode='lines',
            line=dict(color=color, width=2.5),
            fill='tozeroy', fillcolor=color.replace(')', ',0.08)').replace('rgb', 'rgba'),
            name=name, showlegend=False
        ), row=idx, col=1)

        # Vertical scrub line
        fig.add_vline(x=gait_pct, line_dash='dot', line_color='#C9D1D9',
                      line_width=1.5, row=idx, col=1)

        # Dot marker at current position
        current_val = df.iloc[np.abs(df['% Gait Cycle'] - gait_pct).argmin()][col]
        fig.add_trace(go.Scatter(
            x=[gait_pct], y=[current_val], mode='markers',
            marker=dict(color=color, size=10, line=dict(color='white', width=2)),
            showlegend=False, hoverinfo='skip'
        ), row=idx, col=1)

    # Styling
    bg = '#161B22'
    axis_style = dict(
        gridcolor='#21262D', zerolinecolor='#21262D',
        tickfont=dict(color='#484F58', size=10),
    )

    for i in range(1, 4):
        fig.update_yaxes(axis_style, title_text='Force (N)', title_font=dict(color='#484F58', size=11), row=i, col=1)

    fig.update_xaxes(axis_style, row=3, col=1,
                     title_text='% Gait Cycle', title_font=dict(color='#484F58', size=11))

    fig.update_layout(
        paper_bgcolor=bg, plot_bgcolor=bg,
        margin=dict(l=60, r=20, t=30, b=40),
        font=dict(color='#C9D1D9'),
        height=None
    )

    # Subtitle styling
    for ann in fig['layout']['annotations']:
        ann['font'] = dict(color='#8B949E', size=12)

    # ── Metric cards ──
    cards = [
        make_card('Total Fz', fz, 'N', '#58A6FF'),
        make_card('Medial', f_med, 'N', '#3FB950'),
        make_card('Lateral', f_lat, 'N', '#F85149'),
        make_card('Med/Lat Ratio', f_med / max(f_lat, 0.01), '', '#D2A8FF'),
    ]

    return fig, cards, f"Phase: {current_phase}"


if __name__ == '__main__':
    app.run(debug=True, port=8050)
